version : '2'

services:
  web:
      container_name: web
      build: ./
      volumes:
          - /Users/htdocs/web:/var/www
      ports:
          - "80:80"
          - "443:443"
      tty: true
      environment:
        XDEBUG_CONFIG: remote_host=192.168.99.100
      links:
          - postgres
  postgres:
      container_name: postgres
      image: phalcon_postgres
      ports:
          - "5432:5432"
      volumes:
          - /Users/postgres:/var/lib/postgresql
      environment:
          POSTGRES_PASSWORD: 123
          POSTGRES_USER: postgres
